config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops, only: [:index, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'list'
    end
  end
  
  root to: 'shops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, length: { maximum: 40 }
  validates :shop_category_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }

  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :shop_category
end

app/models/shop_category.rb
class ShopCategory < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'cafe' },
    { id: 3, name: 'restaurant' },
    { id: 4, name: '居酒屋' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :shops
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end

  has_many :user_shops
  has_many :shops, through: :user_shops
end

app/models/user_shop.rb
class UserShop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def list
    @shops = Shop.where(shop_category_id: params[:shop_category_id]).order(created_at: :desc)
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(params[:id])
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @shop.destroy
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:image, :shop_category_id, :name, :address, :phone_number, :opening_hours,
                                 :nearest_station, :memo).merge(user_id: current_user.id)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToGoEat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<ul class="shop-categories">
  <% ShopCategory.all.each do |category| %>
    <% unless category.name == '---' %>
      <li><%= link_to category.name, list_shops_path(shop_category_id: category.id), class: 'shop-category' %></li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='top-page-header-contents'>
    <%= link_to 'To Go Eat', root_path, class:'logo' %>
    <ul class='user-lists'>
      <% if user_signed_in?   %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete }, class: "logout" %></li>
     <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login"%></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up"%></li>
     <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='top-page-header'>
  <div class='top-page-header-contents'>
    <%= link_to 'To Go Eat', root_path, class:'logo' %>
  </div>
</header>

app/views/shops/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="edit-shop-form-wrap">
    <h2 class="shop-form-title">行きたいお店を編集</h2>
      <%= form_with model: @shop, class: 'shop-form', local: true do |f| %>
      
        <%= render 'shared/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :shop_category_id, "お店のカテゴリー" %><br />
          <%= f.collection_select(:shop_category_id, ShopCategory.all, :id, :name, {}, {class:"select-box", id:"shop-category"}) %>
        </div>
        <div class="field">
          <%= f.label :name, "お店の名前" %><br />
          <%= f.text_field :name, class:"input-defolt", placeholder:"お店の名前" %>
        </div>
        <div class="field">
          <%= f.label :nearest_station, "最寄駅" %><br />
          <%= f.text_field :nearest_station, class:"input-defolt", placeholder:"最寄駅" %>
        </div>
        <div class="field">
          <%= f.label :opening_hours, "営業時間" %><br />
          <%= f.text_field :opening_hours, class:"input-defolt", placeholder:"営業時間" %>
        </div>
        <div class="field">
          <%= f.label :address, "お店の住所" %><br />
           <%= f.text_field :address, class:"input-defolt", placeholder:"住所" %>
        </div>
        <div class="field">
          <%= f.label :phone_number, "電話番号" %><br />
          <%= f.text_field :phone_number, class:"input-defolt", placeholder:"電話番号" %>
        </div>
        <div class="field">
          <%= f.label :image, "画像" %><br />
          <%= f.file_field :image, class:"shop-image", id:"shop-image" %>
        </div>
        <div class="field">
          <%= f.label :memo, "メモ" %><br />
          <%= f.text_field :memo, class:"input-defolt", placeholder:"メモ" %>
        </div>
          <%= f.submit '追加', class:"add-btn" %>
      <% end %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/shops/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&region=JP&language=ja&libraries=places&callback=initMap" async defer>
    </script>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="main">
      <% if user_signed_in? %>
        <div class="map-and-shop-form-wrap">
          <div id="map">
          </div>
          <div class="shop-form-wrap">
            <h2 class="shop-form-title">行きたいお店を入力</h2>
            <%= form_with model: @shop, class: 'shop-form', local: true do |f| %>
            
              <%= render 'shared/error_messages', model: f.object %>

              <div class="field">
                <%= f.label :shop_category_id, "お店のカテゴリー" %><br />
                <%= f.collection_select(:shop_category_id, ShopCategory.all, :id, :name, {}, {class:"select-box", id:"shop-category"}) %>
              </div>
              <div class="field">
                <%= f.label :name, "お店の名前" %><br />
                <%= f.text_field :name, class:"input-defolt", placeholder:"お店の名前" %>
              </div>
              <div class="field">
                <%= f.label :nearest_station, "最寄駅" %><br />
                <%= f.text_field :nearest_station, class:"input-defolt", placeholder:"最寄駅" %>
              </div>
              <div class="field">
                <%= f.label :opening_hours, "営業時間" %><br />
                <%= f.text_field :opening_hours, class:"input-defolt", placeholder:"営業時間" %>
              </div>
              <div class="field">
                <%= f.label :address, "お店の住所" %><br />
                <%= f.text_field :address, class:"input-defolt", placeholder:"住所" %>
              </div>
              <div class="field">
                <%= f.label :phone_number, "電話番号" %><br />
                <%= f.text_field :phone_number, class:"input-defolt", placeholder:"電話番号" %>
              </div>
              <div class="field">
                <%= f.label :image, "画像" %><br />
                <%= f.file_field :image, class:"shop-image", id:"shop-image" %>
              </div>
              <div class="field">
                <%= f.label :memo, "メモ" %><br />
                <%= f.text_field :memo, class:"input-defolt", placeholder:"メモ" %>
              </div>
                <%= f.submit '追加', class:"add-btn" %>
            <% end %>
          </div>
        </div>
      <% else %>
      <div class="sign-up-message">
        新規登録して始めよう!
      </div>
      <% end %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shops/list.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="shop-list-contents-wrap">
    <% @shops.each do |shop| %>
      <div class='shop-list-content-wrap'>
        <%= link_to shop_path(shop.id), class: "shop-list-link-wrap" do %>
          <div class='shop-img-content'>
            <%= image_tag shop.image, class: "shop-img" %>
          </div>
          <div class="shop-list-content">店名：<%= shop.name %></div>
          <div class="shop-list-content">最寄駅：<%= shop.nearest_station %></div>
          <div class="shop-list-content">営業時間：<%= shop.opening_hours %></div>
        <% end %>
        <div class="shop-list-check_box">
          <%= form_with model: shop, url: shop_path(shop), local: true, method: :patch do |f| %>
            訪問済み
            <%= f.check_box :visited, include_hidden: false %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/shops/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="show-shop-content-wrap">
    <%= image_tag @shop.image, class: "show-shop-content__img" %>
    <div class="show-shop-explain">
      <div class="show-shop-content">店名：<%= @shop.name %></div>
      <div class="show-shop-content">最 寄 駅：<%= @shop.nearest_station %></div>
      <div class="show-shop-content">営業時間：<%= @shop.opening_hours %></div>
      <div class="show-shop-content">住所：<%= @shop.address %></div>
      <div class="show-shop-content">電話：<%= @shop.phone_number%></div>
      <div class="show-shop-content">メモ：<%= @shop.memo%></div>
      <% if (user_signed_in?) && (current_user.id == @shop.user_id) %>
        <%= link_to "お店の編集", edit_shop_path, class: "show-shop-btn" %>
        <%= link_to "お店の削除", shop_path(@shop), data: { turbo_method: :delete }, class: "show-shop-btn" %>
      <% end %>
    </div>
  </div>
  <%= render "shared/footer" %>
</div>